// scratch_restructure_master.js
// Renumbers and recategorizes Python questions generated by scratch_generate_all.js,
// then merges them with scientific_questions.json to create the final localQuestions.ts.

const fs = require('fs');
const path = require('path');

// 1. Run scratch_generate_all.js first to generate the raw 162 Python questions in localQuestions.ts
console.log('Step 1: Generating raw Python questions using scratch_generate_all.js...');
const { execSync } = require('child_process');
execSync('node scratch_generate_all.js', { stdio: 'inherit' });

// 2. Load the newly generated localQuestions.ts
console.log('Step 2: Loading generated Python questions...');
function loadQuestions() {
  const content = fs.readFileSync('src/lib/localQuestions.ts', 'utf8');
  let jsCode = content
    .replace(/export interface[\s\S]*?\n\}/g, '')
    .replace(/export const LOCAL_QUESTIONS:[\s\S]*?=\s*\[/g, 'module.exports = [');
  const tempPath = './temp_local_questions.js';
  fs.writeFileSync(tempPath, jsCode);
  delete require.cache[require.resolve(tempPath)];
  const qs = require(tempPath);
  fs.unlinkSync(tempPath);
  return qs;
}

const rawPythonQs = loadQuestions();

// 3. Exclude variables/basics (IDs 1-10) and scientific categories (to prevent duplication)
let pythonQs = rawPythonQs.filter(q => q.id >= 11 && !['numpy', 'pandas', 'matplotlib-seaborn'].includes(q.category));

// 4. Shift IDs by -10 and assign correct categories
console.log('Step 3: Restructuring Python question categories and IDs...');
const restructuredPythonQs = pythonQs.map(q => {
  const oldId = q.id;
  const newId = oldId - 10;
  
  q.id = newId;
  q.title = q.title.replace(/^\d+\.\s*/, `${newId}. `);
  q.dataset_name = q.dataset_name !== undefined ? q.dataset_name : null;

  // Granular category mapping based on original ID ranges
  if (oldId >= 11 && oldId <= 25) {
    q.category = 'python-ifelse';
  } else if (oldId >= 26 && oldId <= 55) {
    q.category = 'python-loops';
  } else if (oldId >= 56 && oldId <= 77) {
    q.category = 'python-patterns';
  } else if (oldId >= 78 && oldId <= 105) {
    q.category = 'python-strings';
  } else if (oldId >= 106 && oldId <= 145) {
    q.category = 'python-lists-arrays';
  } else if (oldId >= 146 && oldId <= 153) {
    q.category = 'python-dicts';
  } else if (oldId >= 154 && oldId <= 167) {
    // Functional Python and OOP are merged into python-oop
    q.category = 'python-oop';
  }

  // Special case: Pascal's Triangle (shifted ID 152, originally 162) goes to patterns
  if (newId === 152) {
    q.category = 'python-patterns';
  }

  return q;
});

// 5. Load the 128 scientific questions
console.log('Step 4: Loading scientific questions...');
const scientificQs = JSON.parse(fs.readFileSync('scientific_questions.json', 'utf8'));

// Renumber scientific questions starting from the max ID of Python questions (157) + 1 = 158
const maxPythonId = Math.max(...restructuredPythonQs.map(q => q.id));
console.log(`Maximum Python question ID: ${maxPythonId}`);

const restructuredScientificQs = scientificQs.map((q, idx) => {
  const newId = maxPythonId + 1 + idx;
  q.id = newId;
  q.title = q.title.replace(/^\d+\.\s*/, `${newId}. `);
  q.dataset_name = q.dataset_name !== undefined ? q.dataset_name : null;
  return q;
});

// 6. Merge them
const finalList = [...restructuredPythonQs, ...restructuredScientificQs];
console.log(`Total questions in final curriculum: ${finalList.length}`);

// Write back to localQuestions.ts
const newContent = `export interface LocalQuestion {
  id: number
  title: string
  difficulty: 'easy' | 'medium' | 'hard'
  points: number
  category: string
  description: string
  starter_code: string
  dataset_name: string | null
  verification_script?: string
}

export const LOCAL_QUESTIONS: LocalQuestion[] = ${JSON.stringify(finalList, null, 2)};
`;

fs.writeFileSync('src/lib/localQuestions.ts', newContent);
console.log('✓ Saved src/lib/localQuestions.ts');

// Sync with pycode-teacher
const teacherPath = path.join(__dirname, '..', 'pycode-teacher', 'src', 'lib', 'localQuestions.ts');
if (fs.existsSync(path.dirname(teacherPath))) {
  fs.writeFileSync(teacherPath, newContent);
  console.log('✓ Synced localQuestions.ts with pycode-teacher');
}

// ─── WRITE questions_seed.sql ────────────────────────────────
console.log('Generating questions_seed.sql for Supabase seeding...');
let sql = `-- PyCode Student — Full Question Seed
-- Generated automatically. Run in Supabase SQL Editor.

BEGIN;
TRUNCATE public.coding_questions RESTART IDENTITY CASCADE;

`;
finalList.forEach(q => {
  const esc = s => (s || '').replace(/'/g, "''");
  const dv = q.dataset_name ? `'${esc(q.dataset_name)}'` : 'NULL';
  
  // Categorize for DB level (basics vs advanced vs scientific)
  let dbCategory = q.category;
  if (!['numpy', 'pandas', 'matplotlib-seaborn'].includes(dbCategory)) {
    if (['python-ifelse', 'python-loops', 'python-patterns', 'python-strings'].includes(dbCategory)) {
      dbCategory = 'python-basics';
    } else {
      dbCategory = 'python-advanced';
    }
  }
  
  sql += `INSERT INTO public.coding_questions (id,title,description,difficulty,points,category,starter_code,verification_script,dataset_name)
VALUES (${q.id},'${esc(q.title)}','${esc(q.description)}','${q.difficulty}',${q.points},'${dbCategory}','${esc(q.starter_code)}','${esc(q.verification_script||'')}',${dv});\n\n`;
});
sql += 'COMMIT;\n';

// Destination 1: pycode-supabase
const sqlDir1 = path.join(__dirname, '..', 'pycode-supabase');
if (!fs.existsSync(sqlDir1)) fs.mkdirSync(sqlDir1, { recursive: true });
fs.writeFileSync(path.join(sqlDir1, 'questions_seed.sql'), sql);

// Destination 2: supabase (root folder)
const sqlDir2 = path.join(__dirname, '..', 'supabase');
if (!fs.existsSync(sqlDir2)) fs.mkdirSync(sqlDir2, { recursive: true });
fs.writeFileSync(path.join(sqlDir2, 'questions_seed.sql'), sql);

console.log('✓ Saved questions_seed.sql to both destinations');
